clc;
clear;
close all;

%% System to control
s = tf('s');
f_sys = 41.25/(s*(s/66.9)+1);

%% Weighting functions
W1 = tf(ponde_font_ss(-60, 6, 10, 'dB'));
W2 = tf(1e-4);
W3 = tf(1e-4);
W4 = tf(1);

weight_functions = struct(...
    'W1', W1, ...
    'W2', W2, ...
    'W3', W3, ...
    'W4', W4  ...
);


%%
options = struct('simulink_name', 'test_simulink',...
                 'ui', true,...
                 'lsp', logspace(-4, 4, 1000),...
                 'plot_bode_k',   true,...
                 'plot_bode_ol',  false,...
                 'plot_nichols',  false ...
                 );

hinf_api = hinfUi(weight_functions, options);

%%
hinf_api.displayWeightingFunctions();
hinf_api.runSynthesis();
ss_k = hinf_api.getGeneratedController();

%%
W1 = tf(ponde_font_ss(-60, 6, 10, 'dB'));

weight_functions = struct(...
    'W1', W1, ...
    'W2', W2, ...
    'W3', W3, ...
    'W4', W4  ...
);

hinf_api.updateWeightingFunctions(weight_functions)
