clc;
clear;
close all;

%%
f_sys = tf(0.5);

%%
W1 = tf(1);
W2 = tf(1);
W3 = tf(1);

weight_functions = struct(...
    'W1', W1, ...
    'W2', W2, ...
    'W3', W3  ...
);


%%
options = struct('simulink_name', 'test',...
                 'lsp', logspace(-2, 2, 1000),...
                 'plot_bode_k',   true,...
                 'plot_bode_ol',  false,...
                 'plot_nichols',  false ...
                 );

hinf_api = hinfUi(weight_functions, options);

%%
W1 = ponde_font_ss(-60, 6, 10, 'dB');
W2 = tf(1);
W3 = tf(1);

weight_functions = struct(...
    'W1', W1, ...
    'W2', W2, ...
    'W3', W3  ...
);

hinf_api.updateWeightingFunctions(weight_functions)
